# Generated by Django 3.2.25 on 2024-09-22 07:09

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publisher", models.TextField()),
                ("author", models.TextField()),
                ("title", models.CharField(max_length=100)),
                ("book_cover", models.ImageField(blank=True, upload_to="")),
                ("description", models.TextField()),
                ("upload_book", models.FileField(upload_to="")),
                ("add_to_catalog", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "book",
                "verbose_name_plural": "books",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_id",
                    models.CharField(
                        default=core.models.generate_membership_id,
                        editable=False,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("enrolled_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Library User",
                "verbose_name_plural": "Library Users",
                "ordering": ["enrolled_on"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrowed_on", models.DateField(auto_now_add=True)),
                ("duration_in_days", models.PositiveIntegerField()),
                ("return_due_date", models.DateField(blank=True, null=True)),
                ("returned_on", models.DateField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.book"
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(to="core.Category"),
        ),
    ]
